# Generated by Django 2.2.2 on 2019-06-20 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_app', '0002_auto_20190620_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
    ]
